name: chinese_chess
description: A ChineseChess game developed by Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cchess: 0.0.4
  cchess_engine: ^0.0.1
  engine:
    path: plugins/engine
  
  intl:
  cupertino_icons:
  logging:
  file_picker: ^6.0.0
  window_manager: ^0.3.7
  #bitsdojo_window: ^0.1.2
  #filesystem_picker: ^2.0.1
  #file_selector: ^0.8.2
  shirne_dialog:  ^4.5.0
  fast_gbk: ^1.0.0-rc
  universal_html: ^2.0.8
  shared_preferences: ^2.2.0
  flutter_native_splash: ^2.2.7
  
  # soundpool: 2.3.0
  # soundpool_windux: #2.3.0
  #   git:
  #     url: https://github.com/ukasz123/soundpool
  #     ref: windows_linux_support
  #     path: soundpool_windux
      
  audioplayers: ^5.2.0
  #assets_audio_player: ^3.0.4+3
  ffi:
  # win32: 2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  icons_launcher: ^2.1.4
  flutter_lints:

# flutter pub run icons_launcher:create
icons_launcher:
  image_path: "assets/icon/icon.png"
  platforms:
    android:
      enable: true
      adaptive_background_color: "#ffffff"
      adaptive_foreground_image: "assets/icon/icon_foreground.png"
    ios: 
      enable: true
    web: 
      enable: true
      favicon_path: "assets/icon/icon.png"
    macos: 
      enable: true
    windows: 
      enable: true
    linux: 
      enable: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/skins/woods/
    - assets/images/
    - assets/sounds/
